package main

type MediaInfo struct {
	Media struct {
		Ref   string `json:"@ref"`
		Track []struct {
			AlternateGroup           string `json:"AlternateGroup,omitempty"`
			AudioCount               string `json:"AudioCount,omitempty"`
			BitDepth                 string `json:"BitDepth,omitempty"`
			BitRate                  string `json:"BitRate,omitempty"`
			BitRateMaximum           string `json:"BitRate_Maximum,omitempty"`
			BitRateMode              string `json:"BitRate_Mode,omitempty"`
			BufferSize               string `json:"BufferSize,omitempty"`
			ChannelLayout            string `json:"ChannelLayout,omitempty"`
			ChannelPositions         string `json:"ChannelPositions,omitempty"`
			Channels                 string `json:"Channels,omitempty"`
			ChromaSubsampling        string `json:"ChromaSubsampling,omitempty"`
			CodecID                  string `json:"CodecID"`
			CodecIDCompatible        string `json:"CodecID_Compatible,omitempty"`
			ColorSpace               string `json:"ColorSpace,omitempty"`
			ColourDescriptionPresent string `json:"colour_description_present,omitempty"`
			ColourPrimaries          string `json:"colour_primaries,omitempty"`
			ColourRange              string `json:"colour_range,omitempty"`
			CompressionMode          string `json:"Compression_Mode,omitempty"`
			DataSize                 string `json:"DataSize,omitempty"`
			Default                  string `json:"Default,omitempty"`
			DisplayAspectRatio       string `json:"DisplayAspectRatio,omitempty"`
			Duration                 string `json:"Duration"`
			EncodedApplication       string `json:"Encoded_Application,omitempty"`
			EncodedDate              string `json:"Encoded_Date"`
			EncodedLibrary           string `json:"Encoded_Library,omitempty"`
			EncodedLibraryName       string `json:"Encoded_Library_Name,omitempty"`
			EncodedLibrarySettings   string `json:"Encoded_Library_Settings,omitempty"`
			EncodedLibraryVersion    string `json:"Encoded_Library_Version,omitempty"`
			Extra                    struct {
				CodecConfigurationBox string `json:"Codec_configuration_box"`
			} `json:"extra,omitempty"`
			FileExtension           string `json:"FileExtension,omitempty"`
			FileModifiedDate        string `json:"File_Modified_Date,omitempty"`
			FileModifiedDateLocal   string `json:"File_Modified_Date_Local,omitempty"`
			FileSize                string `json:"FileSize,omitempty"`
			FooterSize              string `json:"FooterSize,omitempty"`
			Format                  string `json:"Format"`
			FormatLevel             string `json:"Format_Level,omitempty"`
			FormatProfile           string `json:"Format_Profile"`
			FormatSettingsCABAC     string `json:"Format_Settings_CABAC,omitempty"`
			FormatSettingsGOP       string `json:"Format_Settings_GOP,omitempty"`
			FormatSettingsRefFrames string `json:"Format_Settings_RefFrames,omitempty"`
			FrameCount              string `json:"FrameCount"`
			FrameRate               string `json:"FrameRate"`
			FrameRateMode           string `json:"FrameRate_Mode,omitempty"`
			FrameRateModeOriginal   string `json:"FrameRate_Mode_Original,omitempty"`
			FrameRateOriginal       string `json:"FrameRate_Original,omitempty"`
			HeaderSize              string `json:"HeaderSize,omitempty"`
			Height                  string `json:"Height,omitempty"`
			ID                      string `json:"ID,omitempty"`
			IsStreamable            string `json:"IsStreamable,omitempty"`
			MatrixCoefficients      string `json:"matrix_coefficients,omitempty"`
			Movie                   string `json:"Movie,omitempty"`
			OverallBitRate          string `json:"OverallBitRate,omitempty"`
			OverallBitRateMode      string `json:"OverallBitRate_Mode,omitempty"`
			PixelAspectRatio        string `json:"PixelAspectRatio,omitempty"`
			Rotation                string `json:"Rotation,omitempty"`
			SampledHeight           string `json:"Sampled_Height,omitempty"`
			SampledWidth            string `json:"Sampled_Width,omitempty"`
			SamplesPerFrame         string `json:"SamplesPerFrame,omitempty"`
			SamplingCount           string `json:"SamplingCount,omitempty"`
			SamplingRate            string `json:"SamplingRate,omitempty"`
			ScanType                string `json:"ScanType,omitempty"`
			Standard                string `json:"Standard,omitempty"`
			StoredHeight            string `json:"Stored_Height,omitempty"`
			StreamOrder             string `json:"StreamOrder,omitempty"`
			StreamSize              string `json:"StreamSize"`
			StreamSizeProportion    string `json:"StreamSize_Proportion,omitempty"`
			TaggedDate              string `json:"Tagged_Date"`
			Title                   string `json:"Title,omitempty"`
			TransferCharacteristics string `json:"transfer_characteristics,omitempty"`
			Type                    string `json:"@type"`
			VideoCount              string `json:"VideoCount,omitempty"`
			Width                   string `json:"Width,omitempty"`
		} `json:"track"`
	} `json:"media"`
}
